# the events block is required
events{}

http {
    # include the default mime.types to map file extensions to MIME types
    include /etc/nginx/mime.types;

    server {
        listen 8080;

        root /usr/share/nginx/html;

        location /ui/marketplace-ui/ui/ {
            try_files $uri $uri/ /ui/index.html;
        }

        location /healthz {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
