sonar.host.url=https://sonar.tools.sap

sonar.projectKey=sonarqubeproject-extension-manager-ui
sonar.projectName=sonarqubeproject-extension-manager-ui

sonar.sources=.
sonar.exclusions=**/*.spec.ts

sonar.pullrequest.github.repository=dxp/extension-manager-ui
sonar.javascript.lcov.reportPaths=coverage/lcov.info

