type APIGroup {
  apiVersion: String
  kind: String
  name: String
  preferredVersion: io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoverypreferredVersion
  serverAddressByClientCIDRs: [io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRs]
  versions: [io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoveryversions]
}

type APIGroupEvent {
  object: APIGroup
  type: WatchEventType!
}

input APIGroupInput {
  preferredVersion: io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoverypreferredVersionInput
  serverAddressByClientCIDRs: [io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRsInput]
  versions: [io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoveryversionsInput]
  apiVersion: String
  kind: String
  name: String
}

type APIGroupList {
  continue: String
  items: [APIGroup!]!
  remainingItemCount: Int
  resourceVersion: String
}

type APIVersions {
  apiVersion: String
  kind: String
  serverAddressByClientCIDRs: [io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRs]
  versions: [String]
}

type APIVersionsEvent {
  object: APIVersions
  type: WatchEventType!
}

input APIVersionsInput {
  serverAddressByClientCIDRs: [io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRsInput]
  versions: [String]
  apiVersion: String
  kind: String
}

type DeleteOptions {
  apiVersion: String
  dryRun: [String]
  gracePeriodSeconds: Int
  ignoreStoreReadErrorWithClusterBreakingPotential: Boolean
  kind: String
  orphanDependents: Boolean
  preconditions: io_k8s_apimachinery_pkg_apis_meta_v1_Preconditionspreconditions
  propagationPolicy: String
}

type DeleteOptionsEvent {
  object: DeleteOptions
  type: WatchEventType!
}

input DeleteOptionsInput {
  apiVersion: String
  dryRun: [String]
  gracePeriodSeconds: Int
  ignoreStoreReadErrorWithClusterBreakingPotential: Boolean
  kind: String
  orphanDependents: Boolean
  preconditions: io_k8s_apimachinery_pkg_apis_meta_v1_PreconditionspreconditionsInput
  propagationPolicy: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoverypreferredVersion {
  groupVersion: String
  version: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoverypreferredVersionInput {
  groupVersion: String
  version: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoveryversions {
  groupVersion: String
  version: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_GroupVersionForDiscoveryversionsInput {
  groupVersion: String
  version: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_ListMetametadata {
  continue: String
  remainingItemCount: Int
  resourceVersion: String
  selfLink: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_ListMetametadataInput {
  selfLink: String
  continue: String
  remainingItemCount: Int
  resourceVersion: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_ManagedFieldsEntrymetadatamanagedFields {
  apiVersion: String
  fieldsType: String
  fieldsV1: JSONString
  manager: String
  operation: String
  subresource: String
  time: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_ManagedFieldsEntrymetadatamanagedFieldsInput {
  apiVersion: String
  fieldsType: String
  fieldsV1: JSONString
  manager: String
  operation: String
  subresource: String
  time: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_ObjectMetametadata {
  annotations: StringMapInput
  creationTimestamp: String
  deletionGracePeriodSeconds: Int
  deletionTimestamp: String
  finalizers: [String]
  generateName: String
  generation: Int
  labels: StringMapInput
  managedFields: [io_k8s_apimachinery_pkg_apis_meta_v1_ManagedFieldsEntrymetadatamanagedFields]
  name: String
  namespace: String
  ownerReferences: [io_k8s_apimachinery_pkg_apis_meta_v1_OwnerReferencemetadataownerReferences]
  resourceVersion: String
  selfLink: String
  uid: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_ObjectMetametadataInput {
  deletionGracePeriodSeconds: Int
  labels: StringMapInput
  creationTimestamp: String
  deletionTimestamp: String
  managedFields: [io_k8s_apimachinery_pkg_apis_meta_v1_ManagedFieldsEntrymetadatamanagedFieldsInput]
  annotations: StringMapInput
  namespace: String
  finalizers: [String]
  uid: String
  resourceVersion: String
  ownerReferences: [io_k8s_apimachinery_pkg_apis_meta_v1_OwnerReferencemetadataownerReferencesInput]
  generateName: String
  selfLink: String
  generation: Int
  name: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_OwnerReferencemetadataownerReferences {
  apiVersion: String
  blockOwnerDeletion: Boolean
  controller: Boolean
  kind: String
  name: String
  uid: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_OwnerReferencemetadataownerReferencesInput {
  apiVersion: String
  blockOwnerDeletion: Boolean
  controller: Boolean
  kind: String
  name: String
  uid: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_Preconditionspreconditions {
  resourceVersion: String
  uid: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_PreconditionspreconditionsInput {
  resourceVersion: String
  uid: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRs {
  clientCIDR: String
  serverAddress: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_ServerAddressByClientCIDRserverAddressByClientCIDRsInput {
  clientCIDR: String
  serverAddress: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_StatusCausedetailscauses {
  field: String
  message: String
  reason: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_StatusCausedetailscausesInput {
  message: String
  reason: String
  field: String
}

type io_k8s_apimachinery_pkg_apis_meta_v1_StatusDetailsdetails {
  causes: [io_k8s_apimachinery_pkg_apis_meta_v1_StatusCausedetailscauses]
  group: String
  kind: String
  name: String
  retryAfterSeconds: Int
  uid: String
}

input io_k8s_apimachinery_pkg_apis_meta_v1_StatusDetailsdetailsInput {
  group: String
  kind: String
  name: String
  retryAfterSeconds: Int
  uid: String
  causes: [io_k8s_apimachinery_pkg_apis_meta_v1_StatusCausedetailscausesInput]
}

"""A JSON-serialized string representation of any object."""
scalar JSONString

type MarketplaceEntry {
  apiVersion: String
  kind: String
  metadata: io_k8s_apimachinery_pkg_apis_meta_v1_ObjectMetametadata
  spec: MarketplaceEntryspec
  status: JSONString
}

type MarketplaceEntryEvent {
  object: MarketplaceEntry
  type: WatchEventType!
}

input MarketplaceEntryInput {
  status: JSONString
  apiVersion: String
  kind: String
  metadata: io_k8s_apimachinery_pkg_apis_meta_v1_ObjectMetametadataInput
  spec: MarketplaceEntryspecInput
}

type MarketplaceEntryList {
  continue: String
  items: [MarketplaceEntry!]!
  remainingItemCount: Int
  resourceVersion: String
}

type MarketplaceEntryspec {
  apiExport: MarketplaceEntryspecspecapiExport
  installed: Boolean
  providerMetadata: MarketplaceEntryspecspecproviderMetadata
}

input MarketplaceEntryspecInput {
  apiExport: MarketplaceEntryspecspecapiExportInput
  installed: Boolean
  providerMetadata: MarketplaceEntryspecspecproviderMetadataInput
}

type MarketplaceEntryspecspecapiExport {
  apiVersion: String
  kind: String
  metadata: JSONString
  spec: MarketplaceEntryspecspecapiExportspecapiExportspec
  status: MarketplaceEntryspecspecapiExportspecapiExportstatus
}

input MarketplaceEntryspecspecapiExportInput {
  status: MarketplaceEntryspecspecapiExportspecapiExportstatusInput
  apiVersion: String
  kind: String
  metadata: JSONString
  spec: MarketplaceEntryspecspecapiExportspecapiExportspecInput
}

type MarketplaceEntryspecspecapiExportspecapiExportspec {
  identity: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentity
  latestResourceSchemas: [String]
  maximalPermissionPolicy: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecmaximalPermissionPolicy
  permissionClaims: [MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaims]
}

input MarketplaceEntryspecspecapiExportspecapiExportspecInput {
  maximalPermissionPolicy: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecmaximalPermissionPolicyInput
  permissionClaims: [MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsInput]
  identity: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityInput
  latestResourceSchemas: [String]
}

type MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentity {
  secretRef: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityspecapiExportspecidentitysecretRef_secret_Enhanced
}

input MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityInput {
  secretRef: MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityspecapiExportspecidentitysecretRefInput
}

type MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityspecapiExportspecidentitysecretRef_secret_Enhanced {
  name: String
  namespace: String
}

input MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecidentityspecapiExportspecidentitysecretRefInput {
  name: String
  namespace: String
}

type MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecmaximalPermissionPolicy {
  local: JSONString
}

input MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecmaximalPermissionPolicyInput {
  local: JSONString
}

type MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaims {
  all: Boolean
  group: String
  identityHash: String
  resource: String
  resourceSelector: [MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsspecapiExportspecpermissionClaimsresourceSelector]
}

input MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsInput {
  group: String
  identityHash: String
  resource: String
  resourceSelector: [MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsspecapiExportspecpermissionClaimsresourceSelectorInput]
  all: Boolean
}

type MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsspecapiExportspecpermissionClaimsresourceSelector {
  name: String
  namespace: String
}

input MarketplaceEntryspecspecapiExportspecapiExportspecspecapiExportspecpermissionClaimsspecapiExportspecpermissionClaimsresourceSelectorInput {
  name: String
  namespace: String
}

type MarketplaceEntryspecspecapiExportspecapiExportstatus {
  conditions: [MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusconditions]
  identityHash: String
  virtualWorkspaces: [MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusvirtualWorkspaces]
}

input MarketplaceEntryspecspecapiExportspecapiExportstatusInput {
  identityHash: String
  virtualWorkspaces: [MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusvirtualWorkspacesInput]
  conditions: [MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusconditionsInput]
}

type MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusconditions {
  lastTransitionTime: String
  message: String
  reason: String
  severity: String
  status: String
  type: String
}

input MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusconditionsInput {
  type: String
  lastTransitionTime: String
  message: String
  reason: String
  severity: String
  status: String
}

type MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusvirtualWorkspaces {
  url: String
}

input MarketplaceEntryspecspecapiExportspecapiExportstatusspecapiExportstatusvirtualWorkspacesInput {
  url: String
}

type MarketplaceEntryspecspecproviderMetadata {
  apiVersion: String
  kind: String
  metadata: JSONString
  spec: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspec
  status: JSONString
}

input MarketplaceEntryspecspecproviderMetadataInput {
  spec: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecInput
  status: JSONString
  apiVersion: String
  kind: String
  metadata: JSONString
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspec {
  contacts: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeccontacts]
  data: String
  description: String
  displayName: String
  documentation: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecdocumentation]
  helpCenterData: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspechelpCenterData]
  icon: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecicon
  links: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeclinks]
  preferredSupportChannels: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecpreferredSupportChannels]
  tags: [String]
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecInput {
  icon: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconInput
  links: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeclinksInput]
  preferredSupportChannels: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecpreferredSupportChannelsInput]
  data: String
  displayName: String
  documentation: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecdocumentationInput]
  tags: [String]
  helpCenterData: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspechelpCenterDataInput]
  contacts: [MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeccontactsInput]
  description: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeccontacts {
  displayName: String
  email: String
  role: [String]
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeccontactsInput {
  displayName: String
  email: String
  role: [String]
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecdocumentation {
  displayName: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecdocumentationInput {
  displayName: String
  url: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspechelpCenterData {
  displayName: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspechelpCenterDataInput {
  displayName: String
  url: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecicon {
  dark: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspecicondark
  light: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspeciconlight
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconInput {
  light: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspeciconlightInput
  dark: MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspecicondarkInput
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspecicondark {
  data: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspecicondarkInput {
  url: String
  data: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspeciconlight {
  data: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeciconspecproviderMetadataspeciconlightInput {
  url: String
  data: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeclinks {
  displayName: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspeclinksInput {
  displayName: String
  url: String
}

type MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecpreferredSupportChannels {
  displayName: String
  url: String
}

input MarketplaceEntryspecspecproviderMetadataspecproviderMetadataspecspecproviderMetadataspecpreferredSupportChannelsInput {
  displayName: String
  url: String
}

type MarketplacePlatformMeshIoMutation {
  v1alpha1: MarketplacePlatformMeshIoV1alpha1Mutation
}

type MarketplacePlatformMeshIoQuery {
  v1alpha1: MarketplacePlatformMeshIoV1alpha1Query
}

type MarketplacePlatformMeshIoV1alpha1Mutation {
  createMarketplaceEntry(
    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The object to create or update"""
    object: MarketplaceEntryInput!
  ): MarketplaceEntry
  deleteMarketplaceEntry(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Boolean
  updateMarketplaceEntry(
    """The object to create or update"""
    object: MarketplaceEntryInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The name of the object"""
    name: String!
  ): MarketplaceEntry
}

type MarketplacePlatformMeshIoV1alpha1Query {
  MarketplaceEntries(
    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"

    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String
  ): MarketplaceEntryList!
  MarketplaceEntry(
    """The name of the object"""
    name: String!
  ): MarketplaceEntry!
  MarketplaceEntryYaml(
    """The name of the object"""
    name: String!
  ): String!
}

type Mutation {
  marketplace_platform_mesh_io: MarketplacePlatformMeshIoMutation
  v1: V1Mutation
}

type Query {
  marketplace_platform_mesh_io: MarketplacePlatformMeshIoQuery
  typeByCategory(
    """The name of the object"""
    name: String!
  ): [typeByCategoryObject!]!
  v1: V1Query
}

type Status {
  apiVersion: String
  code: Int
  details: io_k8s_apimachinery_pkg_apis_meta_v1_StatusDetailsdetails
  kind: String
  message: String
  metadata: io_k8s_apimachinery_pkg_apis_meta_v1_ListMetametadata
  reason: String
  status: String
}

type StatusEvent {
  object: Status
  type: WatchEventType!
}

input StatusInput {
  details: io_k8s_apimachinery_pkg_apis_meta_v1_StatusDetailsdetailsInput
  kind: String
  message: String
  metadata: io_k8s_apimachinery_pkg_apis_meta_v1_ListMetametadataInput
  reason: String
  status: String
  apiVersion: String
  code: Int
}

type StatusList {
  continue: String
  items: [Status!]!
  remainingItemCount: Int
  resourceVersion: String
}

"""Input type for a map from strings to strings."""
scalar StringMapInput

type Subscription {
  """Subscribe to changes of MarketplaceEntries"""
  marketplace_platform_mesh_io_v1alpha1_marketplaceentries(
    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"

    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String
  ): MarketplaceEntryEvent

  """Subscribe to changes of MarketplaceEntry"""
  marketplace_platform_mesh_io_v1alpha1_marketplaceentry(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String
  ): MarketplaceEntryEvent

  """Subscribe to changes of APIGroup"""
  v1_apigroup(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String
  ): APIGroupEvent

  """Subscribe to changes of APIGroups"""
  v1_apigroups(
    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"

    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String
  ): APIGroupEvent

  """Subscribe to changes of APIVersions"""
  v1_apiversions(
    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String

    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"
  ): APIVersionsEvent

  """Subscribe to changes of DeleteOptions"""
  v1_deleteoptions(
    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String

    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"
  ): DeleteOptionsEvent

  """Subscribe to changes of Status"""
  v1_status(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String
  ): StatusEvent

  """Subscribe to changes of Statuses"""
  v1_statuses(
    """The field to sort the results by"""
    sortBy: String = "metadata.name"

    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """If true, events will be emitted on every field change"""
    subscribeToAll: Boolean = false

    """
    If set, subscription will stream changes starting from this resourceVersion. If omitted will return all
    """
    resourceVersion: String

    """A label selector to filter the objects by"""
    labelselector: String
  ): StatusEvent
}

type typeByCategoryObject {
  group: String!
  kind: String!
  scope: String!
  version: String!
}

type V1Mutation {
  createAPIGroup(
    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The object to create or update"""
    object: APIGroupInput!
  ): APIGroup
  createAPIVersions(
    """The object to create or update"""
    object: APIVersionsInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): APIVersions
  createDeleteOptions(
    """The object to create or update"""
    object: DeleteOptionsInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): DeleteOptions
  createStatus(
    """The object to create or update"""
    object: StatusInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Status
  deleteAPIGroup(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Boolean
  deleteAPIVersions(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Boolean
  deleteDeleteOptions(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Boolean
  deleteStatus(
    """The name of the object"""
    name: String!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean
  ): Boolean
  updateAPIGroup(
    """The object to create or update"""
    object: APIGroupInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The name of the object"""
    name: String!
  ): APIGroup
  updateAPIVersions(
    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The name of the object"""
    name: String!

    """The object to create or update"""
    object: APIVersionsInput!
  ): APIVersions
  updateDeleteOptions(
    """The object to create or update"""
    object: DeleteOptionsInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The name of the object"""
    name: String!
  ): DeleteOptions
  updateStatus(
    """The object to create or update"""
    object: StatusInput!

    """If true, the operation will be performed in dry-run mode"""
    dryRun: Boolean

    """The name of the object"""
    name: String!
  ): Status
}

type V1Query {
  APIGroup(
    """The name of the object"""
    name: String!
  ): APIGroup!
  APIGroupYaml(
    """The name of the object"""
    name: String!
  ): String!
  APIGroups(
    """Maximum number of items to return (server may return fewer)"""
    limit: Int

    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"
  ): APIGroupList!
  APIVersions(
    """The name of the object"""
    name: String!
  ): APIVersions!
  APIVersionsYaml(
    """The name of the object"""
    name: String!
  ): String!
  DeleteOptions(
    """The name of the object"""
    name: String!
  ): DeleteOptions!
  DeleteOptionsYaml(
    """The name of the object"""
    name: String!
  ): String!
  Status(
    """The name of the object"""
    name: String!
  ): Status!
  StatusYaml(
    """The name of the object"""
    name: String!
  ): String!
  Statuses(
    """Continue token from a previous list call to retrieve the next page"""
    continue: String

    """A label selector to filter the objects by"""
    labelselector: String

    """The field to sort the results by"""
    sortBy: String = "metadata.name"

    """Maximum number of items to return (server may return fewer)"""
    limit: Int
  ): StatusList!
}

"""Event type for resource change notifications"""
enum WatchEventType {
  ADDED
  MODIFIED
  DELETED
}

